# Generated by Django 2.2 on 2021-09-05 07:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_title', models.CharField(blank=True, default='', max_length=128, verbose_name='HTML Title')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='keywords')),
                ('seo_text', models.TextField(blank=True, verbose_name='SEO текст')),
                ('title', models.CharField(max_length=512, verbose_name='Заголовок')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('slug', models.CharField(blank=True, help_text='Оставить пустым, чтобы сгенерировался автоматически', max_length=100, null=True, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'текстовый раздел',
                'verbose_name_plural': 'Текстовые разделы',
            },
        ),
    ]
