# Generated by Django 2.2 on 2021-09-05 07:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.folder


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('on_gallery', models.BooleanField(default=True, verbose_name='Показать в Галерее?')),
                ('link', models.CharField(blank=True, max_length=512, null=True, verbose_name='URL адрес')),
                ('folder', filer.fields.folder.FilerFolderField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Folder', verbose_name='Папка')),
            ],
            options={
                'verbose_name': 'галерея',
                'verbose_name_plural': 'Галерея',
                'ordering': ['-date'],
            },
        ),
    ]
