# Generated by Django 2.2 on 2021-09-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, help_text='Оставить пустым, чтобы сгенерировался автоматически', max_length=100, null=True, unique=True, verbose_name='Слаг')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'категория товаров',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['order'],
            },
        ),
    ]
