# Generated by Django 2.2 on 2021-09-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Заголовок')),
                ('title_block', models.CharField(blank=True, max_length=512, null=True, verbose_name='Заголовок внутри блока')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('slug', models.CharField(blank=True, help_text='Оставить пустым, чтобы сгенерировался автоматически', max_length=100, null=True, unique=True, verbose_name='Слаг')),
                ('category_icon_text', models.TextField(blank=True, null=True, verbose_name='Иконка для категории текстом')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'категория товаров',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['order'],
            },
        ),
    ]
