# Generated by Django 2.2 on 2021-09-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodsCategory',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
