# Generated by Django 2.2 on 2021-09-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210905_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='on_gallery',
        ),
    ]
